########################## 统一变量配置 ##########################
spring: 
  datasource: 
    username: root
    password: Zd(lu7(]yrdtjsmj0qnN>tz2WYVnnrJb
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.90:3606/kk_porn?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowMultiQueries=true

    # username: ${zlt.datasource.username}
    # password: ${zlt.datasource.password}
###### redis配置
  # redis: 
  #   host: 167.179.15.36
  #   port: 6502
  #   password: gk21(O3ieZDxSehCgTQVvmFZuE{ec2z9
  #   timeout: 5000
  #   database: 2
  redis: 
    host: 192.168.100.90
    port: 8000
    password: gk21(O3ieZDxSehCgTQVvmFZuE{ec2z9
    timeout: 5000
    database: 1
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty

zlt:
  ##### 日志链路追踪
  trace: 
    enable: true
  ##### 负载均衡隔离(version隔离，只适用于开发环境)
  ribbon: 
    isolation: 
      enabled: false

  ##### elasticjob分布式定时任务
  elasticjob:
  
    serverLists: 192.168.100.110:2181
    
  ##### minio配置
  minio: 
    access-key: testaccesskey
    accessKeySecret: testsecretkey
    endpoint: http://minio1.165535.net
    bucketName: kkporn
    externalEndpoint: http://minio1.165535.net



##### mybatis-plus打印完整sql(只适用于开发环境)
mybatis-plus: 
  configuration: 
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.alibaba.druid.pool.DruidAbstractDataSource: error