spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: auth-login-token
          uri: lb://uaa-server
          predicates:
            - Path=/api-uaa/oauth/token
          filters:
            - StripPrefix=1
            - PreserveHostHeader
            # - LoginWhiteIpCheck
        # - id: user
        #   uri: lb://user-server
        #   predicates:
        #     - Path=/api-user/**
        #   filters:
        #     - StripPrefix=1
        - id: marksix
          uri: lb://marksix-server
          predicates:
            - Path=/api-marksix/**
          filters:
            - StripPrefix=1   
        - id: backend
          uri: lb://backend-server
          predicates:
            - Path=/platform-backend/**
          filters:
            - StripPrefix=1
            # - BackendWhiteIpCheck
#    sentinel:
#      datasource.ds1.nacos:
#        server-addr: ${spring.cloud.nacos.server-addr}
#        data-id: ${spring.application.name}-sentinel-gw-flow
#        group-id: DEFAULT_GROUP
#        ruleType: gw-flow
#      filter:
#        enabled: true

zlt:
  swagger-agg:
    generate-routes: auth,marksix,backend
    # generate-routes: test
  oauth2:
    token:
      store:
        type: redis
  security:
    ignore:
      # 忽略认证的地址
      httpUrls: >
        /api-uaa/oauth/**,
        /platform-backend/googleCode/**,
        /platform-backend/common/**,
        /api-uaa/validata/**,
        /api-uaa/css/**,
        /api-uaa/images/**,
        /api-uaa/js/**,
        /login.html,
        /user/login,
        /api-uaa/tokens/key,
        /api-config/system/findLogoUrlInfo,
        /api-config/system/getVersion,
        /api-config/sse/**,
        /api-config/api/**,
        /api-push/**,
        /api-business/**,
        /api-porn/v1/site/**,
        /api-porn/v1/movie/**,
        /api-porn/ws/online/**,
        /api-trans/translate/frontFullSource,
        /*/v2/api-docs,
        /swagger/api-docs,
        /swagger-ui.html,
        /doc.html,
        /swagger-resources/**
        
    auth:
      urlPermission:
        #是否开启url级别权限
        enable: false
        #配置只进行登录认证，不进行url权限认证的api
        ignoreUrls: >
          /api-user/menus/current,
          /api-user/users/current,
          /api-log/requestStat
        #白名单
        includeClientIds:
          - webApp
      renew:
        #是否开启token自动续签（目前只有redis实现）
        enable: true
        #白名单
        includeClientIds:
          - webApp
  gateway:
    #网关动态路由
    dynamicRoute:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000